spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/tobby-spring;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.datasource.init: TRACE
server:
  port: 8081
