create table users (
    id bigint generated by default as identity,
    name varchar(20) not null,
    password varchar(20) not null,
    level int not null,
    login int not null,
    recommend int not null,
    primary key (id)
);
